import eslint from "@eslint/js";
import globals from "globals";
import stylistic from "@stylistic/eslint-plugin";
import tseslint from "typescript-eslint";

export default tseslint.config(
    // Global ignores (replaces .eslintignore)
    {
        ignores: ["dist/"],
    },

    // Base recommended configs
    eslint.configs.recommended,
    ...tseslint.configs.recommended,

    // Main config for all JS/TS files
    {
        files: ["**/*.{js,mjs,ts}"],
        plugins: {
            "@stylistic": stylistic,
        },
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: "module",
            globals: {
                ...globals.browser,
                ...globals.es2020,
                ...globals.node,
                Atomics: "readonly",
                SharedArrayBuffer: "readonly",
            },
        },
        rules: {
            // --- Core ESLint rules ---
            "accessor-pairs": "error",
            "array-callback-return": "error",
            "arrow-body-style": "error",
            "block-scoped-var": "error",
            "camelcase": "error",
            "capitalized-comments": "off",
            "class-methods-use-this": "off",
            "complexity": "error",
            "consistent-return": [
                "error",
                { "treatUndefinedAsUnspecified": false },
            ],
            "consistent-this": "error",
            "curly": "error",
            "default-case": "error",
            "default-param-last": "error",
            "dot-notation": "error",
            "eqeqeq": "error",
            "func-name-matching": "error",
            "func-names": "error",
            "func-style": ["error", "declaration", { "allowArrowFunctions": true }],
            "grouped-accessor-pairs": "error",
            "guard-for-in": "error",
            "id-denylist": "error",
            "id-length": "off",
            "id-match": "error",
            "init-declarations": "error",
            "max-classes-per-file": "error",
            "max-depth": "error",
            "max-len": "off",
            "max-lines": "error",
            "max-lines-per-function": "error",
            "max-nested-callbacks": "error",
            "max-params": "off",
            "max-statements": "off",
            "multiline-comment-style": "error",
            "new-cap": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-await-in-loop": "error",
            "no-bitwise": "off",
            "no-caller": "error",
            "no-console": "error",
            "no-constructor-return": "error",
            "no-continue": "error",
            "no-div-regex": "error",
            "no-dupe-else-if": "error",
            "no-duplicate-imports": "error",
            "no-else-return": "error",
            "no-empty-function": "error",
            "no-eq-null": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-implicit-coercion": "error",
            "no-implicit-globals": "error",
            "no-implied-eval": "error",
            "no-import-assign": "error",
            "no-inline-comments": "off",
            "no-invalid-this": "error",
            "no-iterator": "error",
            "no-label-var": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-loop-func": "error",
            "no-magic-numbers": "off",
            "no-multi-assign": "error",
            "no-multi-str": "error",
            "no-negated-condition": "off",
            "no-nested-ternary": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-object-constructor": "error",
            "no-new-wrappers": "error",
            "no-octal-escape": "error",
            "no-param-reassign": "off",
            "no-plusplus": "off",
            "no-proto": "error",
            "no-restricted-globals": "error",
            "no-restricted-imports": "error",
            "no-restricted-properties": "error",
            "no-restricted-syntax": "error",
            "no-return-assign": "error",
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-setter-return": "error",
            "no-shadow": "error",
            "no-template-curly-in-string": "error",
            "no-ternary": "off",
            "no-throw-literal": "error",
            "no-undef-init": "error",
            "no-undefined": "off",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unused-expressions": "error",
            "no-use-before-define": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "no-void": "error",
            "no-warning-comments": "error",
            "object-shorthand": "off",
            "one-var": "off",
            "operator-assignment": "error",
            "prefer-arrow-callback": "error",
            "prefer-const": "error",
            "prefer-destructuring": "error",
            "prefer-exponentiation-operator": "error",
            "prefer-named-capture-group": "error",
            "prefer-numeric-literals": "error",
            "prefer-object-spread": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-regex-literals": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "radix": "error",
            "require-atomic-updates": "error",
            "require-await": "error",
            "require-unicode-regexp": "error",
            "sort-imports": ["error", { "ignoreCase": true }],
            "sort-keys": "off",
            "sort-vars": "error",
            "strict": "error",
            "symbol-description": "error",
            "unicode-bom": ["error", "never"],
            "vars-on-top": "error",
            "yoda": ["error", "never"],

            // --- @stylistic rules (moved from core ESLint) ---
            "@stylistic/array-bracket-newline": ["error", { "multiline": true }],
            "@stylistic/array-bracket-spacing": ["error", "never"],
            "@stylistic/array-element-newline": "off",
            "@stylistic/arrow-parens": "off",
            "@stylistic/arrow-spacing": "error",
            "@stylistic/block-spacing": "error",
            "@stylistic/brace-style": "error",
            "@stylistic/comma-dangle": "off",
            "@stylistic/comma-spacing": [
                "error",
                { "after": true, "before": false },
            ],
            "@stylistic/comma-style": "error",
            "@stylistic/computed-property-spacing": ["error", "never"],
            "@stylistic/dot-location": "error",
            "@stylistic/eol-last": "error",
            "@stylistic/function-call-spacing": "error",
            "@stylistic/function-call-argument-newline": ["error", "consistent"],
            "@stylistic/function-paren-newline": "off",
            "@stylistic/generator-star-spacing": "off",
            "@stylistic/implicit-arrow-linebreak": "error",
            "@stylistic/indent": ["error", 4],
            "@stylistic/jsx-quotes": "error",
            "@stylistic/key-spacing": "error",
            "@stylistic/keyword-spacing": "error",
            "@stylistic/line-comment-position": "off",
            "@stylistic/linebreak-style": ["error", "unix"],
            "@stylistic/lines-around-comment": "error",
            "@stylistic/lines-between-class-members": [
                "error",
                "always",
                { "exceptAfterSingleLine": true },
            ],
            "@stylistic/max-statements-per-line": "error",
            "@stylistic/multiline-ternary": "off",
            "@stylistic/new-parens": "error",
            "@stylistic/newline-per-chained-call": "error",
            "@stylistic/no-confusing-arrow": "off",
            "@stylistic/no-extra-parens": "error",
            "@stylistic/no-floating-decimal": "error",
            "@stylistic/no-mixed-operators": "off",
            "@stylistic/no-multi-spaces": [
                "error",
                { "ignoreEOLComments": true },
            ],
            "@stylistic/no-multiple-empty-lines": "error",
            "@stylistic/no-tabs": "error",
            "@stylistic/no-whitespace-before-property": "error",
            "@stylistic/nonblock-statement-body-position": "error",
            "@stylistic/object-curly-newline": "error",
            "@stylistic/object-curly-spacing": "off",
            "@stylistic/object-property-newline": "off",
            "@stylistic/one-var-declaration-per-line": "error",
            "@stylistic/operator-linebreak": ["error", "after"],
            "@stylistic/padded-blocks": "off",
            "@stylistic/padding-line-between-statements": "error",
            "@stylistic/quote-props": "off",
            "@stylistic/quotes": ["error", "double"],
            "@stylistic/rest-spread-spacing": "error",
            "@stylistic/semi": "error",
            "@stylistic/semi-spacing": [
                "error",
                { "after": true, "before": false },
            ],
            "@stylistic/semi-style": ["error", "last"],
            "@stylistic/space-before-blocks": "error",
            "@stylistic/space-before-function-paren": [
                "error",
                { "anonymous": "always", "named": "never", "asyncArrow": "always" },
            ],
            "@stylistic/space-in-parens": "error",
            "@stylistic/space-infix-ops": "error",
            "@stylistic/space-unary-ops": [
                "error",
                { "nonwords": false, "words": true },
            ],
            "@stylistic/spaced-comment": ["error", "always"],
            "@stylistic/switch-colon-spacing": "error",
            "@stylistic/template-curly-spacing": ["error", "never"],
            "@stylistic/template-tag-spacing": "error",
            "@stylistic/wrap-iife": ["error", "inside"],
            "@stylistic/wrap-regex": "error",
            "@stylistic/yield-star-spacing": "error",
        },
    },
);
