name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      dry-run:
        description: "Dry run (skip actual publish)"
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for OIDC npm publish
                       # Check https://docs.npmjs.com/trusted-publishers
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set version
        id: set-version
        run: echo "new-tag=$(npm version ${{ inputs.version }})" >> "$GITHUB_OUTPUT"

      - name: Push commit and tag
        if: ${{ !inputs.dry-run }}
        run: git push origin HEAD "${{ steps.set-version.outputs.new-tag }}"

      - name: Update version badge
        if: ${{ !inputs.dry-run }}
        uses: ./.github/actions/update-version-badge

      - uses: ./.github/actions/publish
        with:
          dry-run: ${{ inputs.dry-run }}
